### ISSUE TITLE
DPMeans missing module "sklearn.utils._readonly_array_wrapper"

### ISSUE THREAD

**Issue by lexipalmer13** [hanshanley/narrative-influence#1]
Really appreciate you making this code available!

I ran into an issue, though, where DPMeans (in particular the predict function) uses ReadOnlyArrayWrapper from sklean.utils - however the file _readonly_array_wrapper is not in the sklearn git repository - at least that I could find (installed from source and checked on github). Do you have any suggestions?

Any help would be much appreciated!

**Comment by hanshanley** [comment]
Hey I have only just started to add code to this repository (sorry, I should have made it private when I created it), but Dp-Means for this purpose was adapted from https://github.com/BGU-CS-VIL/pdc-dp-means. In order to make work for my purpose though, I had to edit it to use cosine similarity however (and change some of the implementation details)

**Comment by lexipalmer13** [comment]
Gotcha - I saw this paper at TADA and have been trying to do a similar task (cluster semantically similar sentences) for a different purpose so wanted to try it out. But if it's not public yet, no worries!

**Comment by hanshanley** [comment]
Absolutely, no worries; If it is not that many sentences (not more than say 20-30K), you may want to look at my other paper https://ojs.aaai.org/index.php/ICWSM/article/view/22149  that uses the BERTopic approach.

**Comment by lexipalmer13** [comment]
Yes, will check it out thanks!
